# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://fabricmc.net/develop
    loom_version=1.17-SNAPSHOT
	minecraft_version=26.2
	loader_version=0.19.2

# Dependencies
	mod_menu_version = 20.0.1

# Mod Properties
	mod_version = 1.2.2
	maven_group = com.lx862
	archives_base_name = splashfox

# Fabric API
fabric_version=0.155.0+26.2